apiVersion: v1
kind: Service
metadata:
  labels:
    app: quobyte
    role: webconsole-api
  name: quobyte-webconsole-api
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
    - name: api
      port: 7860
      protocol: TCP
  selector:
    app: quobyte
    role: webconsole-api
