apiVersion: v1
kind: Pod
metadata:
  name: quobyte-server-sleep
spec:
  nodeSelector:
    quobyte: registry
  containers:
  - name: quobyte-server-sleep
    image: quobyte-server:1.2.6
    args:
    - sleep
    - "1000000"
    securityContext:
      privileged: true
    env:
      - name: QUOBYTE_SERVICE
        value: "api"
      - name: QUOBYTE_API_PORT
        value: "7860"
      - name: QUOBYTE_REGISTRY
        value: quobyte-registry:7866
    ports:
      - name: http
        containerPort: 8080
        protocol: TCP
    volumeMounts:
      - name: devicedir
        mountPath: /devices
  volumes:
  - name: devicedir
    hostPath:
      path: /mnt
# kubectl exec -ti quobyte-server-sleep sh
