apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: quobyte-client
  labels:
    app: quobyte
    role: client
spec:
  template:
    metadata:
      labels:
        app: quobyte
        role: client
    spec:
#      nodeSelector:
#        quobyte: client
      containers:
      - name: quobyte-client
        image: quobyte-client:1.2.6
        command: [ "/bin/mount.quobyte", "-f", "-d $(QUOBYTE_CLIENT_LOG_LEVEL)", "$(QUOBYTE_REGISTRY)/", "$(QUOBYTE_MOUNT_POINT)" ]
        securityContext:
          privileged: true
        env:
          - name: QUOBYTE_CLIENT_HTTP_PORT
            value: "55000"
          - name: QUOBYTE_CLIENT_LOG_LEVEL
            value: "INFO"
          - name: QUOBYTE_REGISTRY
            value: quobyte-registry:7866
          - name: QUOBYTE_MOUNT_POINT
            value: /quobyte/mnt
# liveness probe?
        ports:
          - name: http-port
            containerPort: 55000
            hostPort: 55000
            protocol: TCP
        volumeMounts:
          - name: mountdir
            mountPath: /quobyte/mnt
#/mnt/dev2:/quobyte/mnt:shared
      volumes:
      - name: mountdir
        hostPath:
          path: /mnt/dev2
