apiVersion: v1
kind: Service
metadata:
  labels:
    app: quobyte
    role: registry
  name: quobyte-registry
spec:
  ports:
    - name: rpc-tcp
      port: 7866
      protocol: TCP
    - name: rpc-udp
      port: 7866
      protocol: UDP
    - name: http
      port: 7876
      protocol: TCP
  selector:
    app: quobyte
    role: registry
