---
- hosts: machines
  sudo: yes
  tasks:
  - name: Copy JRE8 package
    copy: src=jre_8-2_all.deb dest=/tmp/jre_8-2_all.deb

  - name: Install JRE8 
    apt: deb=/tmp/jre_8-2_all.deb
 
  - name: setup ppa repository on Ubuntu
    apt_repository: repo="ppa:webupd8team/java"

  - name: Import Quobyte USP repo key
    apt_key: url={{repository}}/Release.key state=present

  - name: setup repository on Ubuntu
    apt_repository: repo="deb {{repository}} ./" state=present

  - name: install services on Ubuntu
    apt: name=quobyte-usp-server state=present update_cache=yes

  - name: install client and tools on Ubuntu
    apt: name=quobyte-usp-client state=present update_cache=yes

  - name: Assures /etc/quobyte dir exists
    file: path=/etc/quobyte state=directory

  - name: install host.cfg
    template: src=host.cfg dest=/etc/quobyte/host.cfg

  - name: create bind test mountpoints
    file: path=/{{ item }} state=directory
    with_items:
      - /test_dev_r
      - /test_dev_m
      - /test_dev_d
    when: test_devices is defined

  - name: create bind test data dirs
    file: path=/{{ item }} state=directory
    with_items:
      - /tmp/test_dev_r
      - /tmp/test_dev_m
      - /tmp/test_dev_d
    when: test_devices is defined

  - name: Check for test device mounts
    command: grep '/test_dev_' /proc/mounts
    register: grep_temp_mount
    always_run: true
    failed_when: grep_temp_mount.rc > 1 
 
  - name: Mount test devices with mount bind
    shell: mount --bind /tmp{{ item }} {{ item }}
    with_items:
      - /test_dev_r
      - /test_dev_m
      - /test_dev_d
    when: test_devices is defined and grep_temp_mount.rc == 1

  - name: Create bootstrap device
    shell: qbootstrap -y {{bootstrap_device}} creates={{bootstrap_device}}/QUOBYTE_DEV_SETUP
    when: bootstrap_device is defined

  - name: Start bootstrap registry service
    service: name=quobyte-dir state=started enabled=yes
    when: bootstrap_device is defined

  - name: Start Web console
    service: name=quobyte-webconsole state=started enabled=yes
    when: bootstrap_device is defined

  - name: Start API services
    service: name=quobyte-api state=started enabled=yes
    when: bootstrap_device is defined

  - name: Prepare other registry devices
    shell: qmkdev -t REGISTRY {{registry_device}} creates={{registry_device}}/QUOBYTE_DEV_SETUP
    when: registry_device is defined

  - name: Start replicated registry services
    service: name=quobyte-dir state=started enabled=yes
    when: registry_device is defined

  - name: Wait for registry devices to come up
    pause: minutes=1

  - name: Add registry replica devices
    shell: qmgmt registry add {{ item }}
    with_items:
      - 2
      - 3
    when: bootstrap_device is defined


  - name: Initialize metadata devices
    shell: qmkdev -t METADATA {{metadata_device}} creates={{metadata_device}}/QUOBYTE_DEV_SETUP
    when: metadata_device is defined

  - name: Start metadata services
    service: name=quobyte-mrc state=started enabled=yes
    when: metadata_device is defined

  - name: Initialize data devices
    shell: qmkdev -t DATA {{data_device}} creates={{data_device}}/QUOBYTE_DEV_SETUP
    when: data_device is defined

  - name: Start data services
    service: name=quobyte-osd state=started enabled=yes
    when: data_device is defined
