apiVersion: v1
kind: Pod
metadata:
  labels:
    role: qmgmt-pod
    version: "2.0.pre"
  name: qmgmt-pod
  namespace: quobyte
spec:
  containers:
    - name: qmgmt-pod
      image: quay.io/quobyte/quobyte-server:2.0.pre
      command:
        - /bin/bash
        - -xec
        - |
          tail -f /dev/null
