apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: registry
  namespace: quobyte
spec:
  template:
    metadata:
      labels:
        role: registry
        version: "2.0.pre4"
    spec:
      containers:
        - name: quobyte-registry
          image: quay.io/quobyte/quobyte-server:2.0.pre4
          # resources:
          #   limits:
          #     memory: "512Mi"
          #     cpu: "100m"

          # priviliged is required for full device inspector support
          securityContext:
            privileged: true
          env:
            - name: QUOBYTE_SERVICE
              value: registry
            - name: QUOBYTE_REGISTRY
              value: registry
            - name: QUOBYTE_EXTRA_SERVICE_CONFIG
              value: >
                constants.automation.manage_registry_replicas=true
            - name: MAX_MEM
              valueFrom:
                configMapKeyRef:
                  name: quobyte-config
                  key: registry.max_mem
            - name: MIN_MEM
              valueFrom:
                configMapKeyRef:
                  name: quobyte-config
                  key: registry.min_mem
          ports:
            - name: rpc-tcp
              containerPort: 7861
              protocol: TCP
            - name: rpc-udp
              containerPort: 7861
              protocol: UDP
            - name: http
              containerPort: 7871
              protocol: TCP
          volumeMounts:
            - mountPath: /dev
              name: dev
            - mountPath: /sys/bus
              name: sysbus
            - mountPath: /lib/modules
              name: libmodules
            - mountPath: /var/lib/quobyte
              name: var-lib-quobyte
              mountPropagation: Bidirectional
            - mountPath: /mnt/quobyte
              name: mnt-quobyte
          readinessProbe:
            timeoutSeconds: 5
            httpGet:
              port: 7871
              path: /
          livenessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 5
            httpGet:
              port: 7871
              path: /
      nodeSelector:
        quobyte_registry: "true"
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: sysbus
          hostPath:
            path: /sys/bus
        - name: libmodules
          hostPath:
            path: /lib/modules
        - name: mnt-quobyte
          hostPath:
            path: /mnt/quobyte
        - name: var-lib-quobyte
          hostPath:
            path: /var/lib/quobyte
